### PR TITLE
New categories under Trakt: My Shows and My Next Episodes && Mark watched episodes and movies in Trakt

### PR DESCRIPTION
**Pull request by charly3pins**
I've added two new categories under Shows/Trakt section.

- My Shows: All TV Shows that the users have been watched in Trakt
- My Next Episodes: The next episodes of TV Shows that the users are watching in Trakt

scakemyer/plugin.video.quasar#580
scakemyer/plugin.video.quasar#607

TODO: update the resources/languages of plugin to change the "My shows" and "My next episodes" label for the corresponding LOCALIZE

I added new changes for when a user finishes to watch a movie or an episode, is marked automatically as watched in Trakt

### CODE REVIEW

**Comment by elgatito** [comment]
@scakemyer usually asks to follow this rule:
- one PR = One feature = one branch = = one commit

**Comment by charly3pins** [comment]
@elgatito thanks for the comment, but i think @scakemyer is no longer active... for the moment I will  no change it..

**Comment by Janhouse** [comment]
Indeed, it does look like someone else will have to take over it / fork. @elgatito seems like you are pretty active, maybe you want to do it?

**Comment by charly3pins** [comment]
@Janhouse i have my own fork with these new features and other minor fixes, I don't know if @elgatito want to collaborate with it or doing alone or something else

**Comment by Janhouse** [comment]
@charly3pins cool, I'll check out your changes. Could you possibly publish some release builds on github with your changes then?
Also, is there some irc chat for quasar? I joined #quasar on freenode IRC but I am the only one there.

**Comment by charly3pins** [comment]
I published here https://github.com/charly3pins/quasar-binaries/tree/TraktIntegration few weeks ago and the chat for quasar is https://gitter.im/QuasarHQ/Lobby

**Pull request closed without merging**
