### PR TITLE
Allow index on uri

### PR DESCRIPTION
**Pull request by i96751414**

### CODE REVIEW

**Comment by scakemyer** [comment]
You are rocking this, geez.

**Comment by i96751414** [comment]
You can close this: https://github.com/scakemyer/plugin.video.quasar/issues/36 :)

**Comment by scakemyer** [comment]
Nicely done, I'll release beta1 after merging this. Although multi-file works great, it's kinda hard to put to use right now. But still, it'll be in the release notes ;)

**Comment by i96751414** [comment]
Yeah, I agree. Providers will need some changes. Also, we need to add a new method to providers' API (`getFiles`)

**Pull request merged**
