### PR TITLE
Support for multi-file torrents

### LINKED ISSUE #1: Support for multi-file torrents
Tobe able to select individual video files for playback.

### PR DESCRIPTION
**Pull request by i96751414**
This will fix #1. Anyway, I think providers are blocking multi-file torrents...

### CODE REVIEW

**Comment by scakemyer** [comment]
nitpick but, choosen -> chosen

**Comment by i96751414** [comment]
Lol, you're right! Going to change that right now. My bad

**Comment by scakemyer** [comment]
Awesome work again, will test it out in a few minutes. How do you like the new builds? ;) Just so you know, to build `quasar` locally for your platform, just use something like `make windows-x64` instead of the previous `make build TARGET_OS=windows TARGET_ARCH=x64 MARGS="dist"`. Hope you like :)

**Comment by i96751414** [comment]
I like this way much more than the other! It simplifies a lot. Btw, there are small things you should change in your dockerfiles (like including the maintainer name)... I can make a PR tomorrow with those changes

**Comment by scakemyer** [comment]
Nice, glad you like! Regarding the maintainer line, it's just not necessary and quite annoying to fix when forking or merging. What other changes were you proposing? Maybe open an issue in the libtorrent-go repo?

**Comment by i96751414** [comment]
Imagine you want to store your images on Docker Hub. Currently I think you can't do that because they have the wrong structure. For example, their name should be: `<user>/<imagename>`

**Comment by scakemyer** [comment]
That's already taken care of by the Travis builds ;) Look into `.travis.yml`, it tags them appropriately before pushing, and tags them after pulling to use them. It's just cleaner to do it that way, especially for those that want to build the images themselves.

**Comment by i96751414** [comment]
Oh, I didn't see that...

**Comment by scakemyer** [comment]
For reference: scakemyer/plugin.video.quasar#17 and scakemyer/plugin.video.quasar#30

**Pull request merged**
