### PR TITLE
Library Integration

### PR DESCRIPTION
**Pull request by i96751414**

### CODE REVIEW

**Comment by i96751414** [comment]
About this one, I know it's your fork, but please don't make any changes without notifying me.

**Comment by scakemyer** [comment]
I wasn't, this is impressive work.

**Comment by scakemyer** [comment]
Want it merged right now or would like to add other commits?

**Comment by i96751414** [comment]
:) Glad you like

**Comment by i96751414** [comment]
You can merge it. Later (today) I will send another PR

**Comment by scakemyer** [comment]
Sounds good. Again, nice work on this. Now you maintain the feature ;)

**Comment by scakemyer** [comment]
Fixed scakemyer/plugin.video.quasar#11, related PR was scakemyer/plugin.video.quasar#21

**Pull request merged**
